steps:
  - name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: gsutil
    args:
      - cp
      - gs://cdsframework-settings/settings.xml
      - /root/.m2
    volumes:
      - name: m2
        path: /root/.m2
  - name: 'maven:3.6.1-jdk-8'
    entrypoint: 'mvn'
    args: [ 'clean', 'deploy', '-DaltDeploymentRepository=support.hln.com-snapshots::default::https://hlnconsulting.jfrog.io/artifactory/libs-snapshot-local' ]
    dir: '.'
    volumes:
      - name: m2
        path: /root/.m2
