name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Copy settings.xml
      run: |
          mkdir -p ~/.m2
          cp .github/resources/settings.xml ~/.m2
    - name: Build with Maven
      run: mvn deploy -Dregistry=https://nicolary:${{ secrets.GHTOKEN }}@maven.pkg.github.com/cdsframework -Dtoken=${{ secrets.GITHUB_TOKEN }}
